### ISSUE TITLE
Arabic and Russian Subtitles are showing as squares

### ISSUE THREAD

**Issue by Michelangelo1337** [animeloyalty/animeloyalty#7] opened 2021-02-03 13:57 UTC
Hey, I was doing some testing yesterday and I noticed that the arabic and the russian subtitles are showing as squares. Since these languages are not well supported on non arabic and russian windows speakers my guess is they should be converted to UTF 8. And as always thanks for the amazing work.

**Comment by Deathspike** [comment] 2021-02-03 17:42
Thank you for testing!

I've confirmed the Arabic subtitle issue on Dr. Stone episode 1. It's because the subtitle worker (libass) tries and fails to load the Arabic symbols. I probably didn't configure the worker properly, but since documentation is so scarce, it's going to be annoying to fix. I did see the Russian subtitles without issues though. Can you tell me which series/episode you've had trouble on with Russian?

**Comment by Michelangelo1337** [comment] 2021-02-04 20:04
> 
> 
> Thank you for testing!
> 
> I've confirmed the Arabic subtitle issue on Dr. Stone episode 1. It's because the subtitle worker (libass) tries and fails to load the Arabic symbols. I probably didn't configure the worker properly, but since documentation is so scarce, it's going to be annoying to fix. I did see the Russian subtitles without issues though. Can you tell me which series/episode you've had trouble on with Russian?

I honestly do not remember which episode I saw the russian subtitle on but I tested now on Boruto and its working so maybe it was just some random epsiode. I can not confirm if its an issue for russian subtitle but its def an issue for the arabic subtitle.

**Comment by Deathspike** [comment] 2021-02-13 19:51
Since I can't read Arabic, I can only hope that this looks correct. If anyone can confirm this, please do.

![image](https://user-images.githubusercontent.com/198601/107859942-1340b400-6e3d-11eb-8528-20c702a5e67c.png)

Fixed in `0.10.0`.

**Closed by Deathspike** 2021-02-13 19:51 UTC
Labels: project:client, type:bug
